# это обязательная декларация; версию ставьте ту, которая у вас установлена
cmake_minimum_required(VERSION 4.3.4)

# имя проекта; не путать с именами target'ов, которые мы собираем
project(finite_state_machine)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# во время разработки ставим Debug; когда выпускаем версию, ставим Release
set(CMAKE_BUILD_TYPE Debug)


# ОПЦИИ позволяют удобно включать и выключать действия системы сборки
# эта опция отвечает за то, собираем ли тесты
# чтобы собрать тесты, надо выставить ON
# также нужно будет очистить build/ и заново сгенерировать файлы для cmake ("cmake .." из build/)

# но на некоторых версиях это не сработает и нужно генерить файлы cmake командой
# cmake -D BUILD_TESTS=ON ..
# а билд как обычно, cmake --build .

option(BUILD_TESTS OFF)

# экспорт команд компиляции - очень полезная функция, если используете языковой сервер
# или вам нужно быстро передать команды сборки куда-то еще
# для практики это необязательно, но очень рекомендую ознакомиться с clangd от llvm project
# set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

# конструкции add_subdirectory означают, что мы учитываем CMakeLists.txt в этих директориях
# можно все декларации для системы сборки написать в корневом CMakeLists.txt,
# но раскиданные по соответствующим папкам куда проще читать и править

# собираем библиотеку
add_subdirectory(src)
# собираем приложение
add_subdirectory(app)

# если опция ON, то собираем тесты
if(BUILD_TESTS)
  add_subdirectory(tests)
endif(BUILD_TESTS)

# в cmake на самом деле безумное количество возможностей
# если есть желание узнать лучшие практики и продвинутый функционал, читайте книгу Professional CMake
# в рамках этого примера я показываю только самое нужное